apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cloudant-extractor
  labels:
    app: cloudant-extractor
spec:
  output:
    to:
      kind: ImageStreamTag
      name: cloudant-extractor:latest
  source:
    type: Git
    git:
      uri: https://github.com/bodarajeshkumar/dormant_id_check.git
      ref: rajesh-changes
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openshift
  triggers:
  - type: ConfigChange
  - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cloudant-extractor
  labels:
    app: cloudant-extractor
spec:
  lookupPolicy:
    local: false

# Made with Bob
