apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudant-extractor

resources:
- secret.yaml
- buildconfig.yaml
- deployment.yaml
- service.yaml
- route.yaml

commonLabels:
  app: cloudant-extractor
  app.kubernetes.io/name: cloudant-extractor
  app.kubernetes.io/component: web
  app.kubernetes.io/part-of: cloudant-extraction-pipeline

images:
- name: cloudant-extractor
  newTag: latest

# Made with Bob
