apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudant-extraction-data
  labels:
    app: cloudant-extractor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudant-status-data
  labels:
    app: cloudant-extractor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudant-history-data
  labels:
    app: cloudant-extractor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Made with Bob
